"""replace_adjustment_with_parsed_adjustment_and_unit_selections

Revision ID: 6299f26a1c0e
Revises: 14c9f59d1ffd
Create Date: 2025-07-10 01:05:21.372534

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6299f26a1c0e"
down_revision = "14c9f59d1ffd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parsedadjustment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("date", sa.String(), nullable=True),
        sa.Column("bill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "adjustmentunitselection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("adjustment_id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["adjustment_id"],
            ["parsedadjustment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("adjustment")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adjustment",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=False),
        sa.Column("cost", sa.FLOAT(), nullable=False),
        sa.Column("unit_id", sa.INTEGER(), nullable=True),
        sa.Column("bill_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("adjustmentunitselection")
    op.drop_table("parsedadjustment")
    # ### end Alembic commands ###
