"""Remove Invoice and LineItem models and add SubMeterReading and Adjustment models

Revision ID: 14c9f59d1ffd
Revises: 72e6404685d0
Create Date: 2025-07-07 01:16:33.004425

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "14c9f59d1ffd"
down_revision = "72e6404685d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adjustment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=True),
        sa.Column("bill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "submeterreading",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reading", sa.Float(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("bill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("lineitem")
    op.drop_table("invoice")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("total_amount", sa.FLOAT(), nullable=False),
        sa.Column("payment_status", sa.VARCHAR(), nullable=False),
        sa.Column("unit_id", sa.INTEGER(), nullable=False),
        sa.Column("bill_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["unit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lineitem",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=False),
        sa.Column("cost", sa.FLOAT(), nullable=False),
        sa.Column("is_adjustment", sa.BOOLEAN(), nullable=False),
        sa.Column("invoice_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("submeterreading")
    op.drop_table("adjustment")
    # ### end Alembic commands ###
